### PR TITLE
Added force renewal + --dns-duckdns-no-txt-restore

### PR DESCRIPTION
**Pull request by devedse**
This should fix:
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/3138

@jc21 up to you if this is the right way to fix it.

### CODE REVIEW

**Comment by jc21** [comment]
Seems fine to me. Let me know if this image works for you.

**Comment by devedse** [comment]
I'll give it a try. Do you know enough about certbot to be able to explain why my change is needed 😄 ?

**Comment by jc21** [comment]
Well, no I don't know why _not_ restoring the original TXT record would be the answer to this problem. I fully understand the DNS verifiction process, but I feel that the devs of the duckdns certbot might have a bug there.

**Comment by devedse** [comment]
I just tried it with the normal unchanged code (:latest image) and it works again... wtf... My guess is that DuckDNS can be in a specific corrupted state or something where we need need to not restore the OriginalTxtRecord???

It might still be good to merge this since it apparently can fix the issue.

**Comment by g1za** [comment]
Hello,
I'm now getting the following error:
`CommandError: usage: 
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate. 
certbot: error: unrecognized arguments: --dns-duckdns-credentials /etc/letsencrypt/credentials/credentials-113 --dns-duckdns-no-txt-restore

    at /app/lib/utils.js:16:13
    at ChildProcess.exithandler (node:child_process:410:5)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`
    
Did they maybe changed anything on DuckDNS side and `--dns-duckdns-no-txt-restore` is not needed anymore?
Let me know if you think it is the right way and I can create a new PR (sorry but I'm not sure I can test on my machine).
Thanks!

**Pull request merged**
