### PR TITLE
Add wedos dns

### PR DESCRIPTION
**Pull request by Hadatko**
Hello, i would like to add another one certbot plugin. How can i test this change?

### CODE REVIEW

**Comment by Hadatko** [comment]
I tested this by manually updating files in my docker instance. It looks working, but the wedos certbot script need little update.

**Comment by Hadatko** [comment]
Hello, with docker image i am getting error:
image

```
[6/29/2024] [11:29:56 PM] [Global   ] › ⬤  debug     CMD: certbot certonly --config "/etc/letsencrypt.ini" --work-dir "/tmp/letsencrypt-lib" --logs-dir "/tmp/letsencrypt-log" --cert-name "npm-12" --agree-tos --email "someemail" --domains "somedomain.somehost.eu" --authenticator dns-wedos --dns-wedos-credentials "/etc/letsencrypt/credentials/credentials-12"
[6/29/2024] [11:29:59 PM] [Global   ] › ⬤  debug     CMD: rm -f '/etc/letsencrypt/credentials/credentials-12' || true
[6/29/2024] [11:29:59 PM] [Global   ] › ⬤  debug     CMD: /usr/sbin/nginx -t -g "error_log off;"
[6/29/2024] [11:29:59 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[6/29/2024] [11:29:59 PM] [Global   ] › ⬤  debug     CMD: /usr/sbin/nginx -s reload
[6/29/2024] [11:29:59 PM] [Express  ] › ⚠  warning   Saving debug log to /tmp/letsencrypt-log/letsencrypt.log
An unexpected error occurred:
PermissionError: [Errno 13] Permission denied: '/etc/letsencrypt/live/README'
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/letsencrypt-log/letsencrypt.log or re-run Certbot with -v for more details.
```

**Comment by Hadatko** [comment]
archive and live folder were created with owner root:root. When i change them to npm:npm, plugin worked well

So ready for merge

**Comment by vsisl** [comment]
Hi @Hadatko 

Thanks a lot for adding this feature!

I just went through setting it up for the first time and I was struggling a bit so I though I'll post here some tips for others...

First of all make sure that the changes implemented in this PR are present in the docker image you're using. As of now, I used the following `docker-compose.yml`:

```yml
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:github-develop' # TODO: switch to latest; using develop so that I have access to this: https://github.com/NginxProxyManager/nginx-proxy-manager/pull/3827
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
```

DNS settings to set up **before** starting the challenge:

SCR-20241003-oqlj

Challenge settings:

Screenshot 2024-10-03 at 16 30 09

With the challenge settings I was slightly confused with the placeholder `<wapi_sha256_password>`. I first tried to paste there she sha256 sum of my wedos WAPI password:

```bash
echo -n 'my_password' | sha256sum
```

But that didn't work. Eventually, I used my wedos WAPI password (plain text) and that worked.

**Note: For a while you might be stuck with a something that looks like an error in the NPM web UI. Just be patient and check your logs. Eventually the certificate landed successfully.**

**Comment by Hadatko** [comment]
Hi @vsisl , as you can see my last comment is saying that everything works and then the feature was merged. Happy to see somebody else to try this  :D

**Pull request merged**
