### PR TITLE
PROXY Protocol support

### PR DESCRIPTION
**Pull request by jwklijnsma**
https://github.com/NginxProxyManager/nginx-proxy-manager/pull/1882 update code base

### CODE REVIEW

**Comment by jwklijnsma** [comment]
@jc21  where can i fine the output of the failed test ?

**Comment by Morriz** [comment]
bump

**Comment by jc21** [comment]
```
CypressError: `cy.task('backendApiPost')` failed with the following error:

> 400: tag "endif" not found, file:/app/templates/_listen.conf, line:20, col:1, line:12, col:1
```

**Comment by jwklijnsma** [comment]
> ```
> CypressError: `cy.task('backendApiPost')` failed with the following error:
> 
> > 400: tag "endif" not found, file:/app/templates/_listen.conf, line:20, col:1, line:12, col:1
> ```
What for test is this in the background ?

**Comment by jc21** [comment]
```
Integration Tests / Mysql / Hosts endpoints.Should be able to create a http host

Error Message:
data should NOT have additional properties
```

There is a swagger/openapi schema file that acts as a contract for the API, can be [found here](https://github.com/NginxProxyManager/nginx-proxy-manager/blob/develop/backend/doc/api.swagger.json). This isn't generated from code on purpose, as it's meant to prevent people making breaking changes by accident.

To get past this, since you're adding new fields to the responses of endpoints, you'll need to define them in the swagger file as well.

**Pull request closed without merging**
