### PR TITLE
http2 directive migration

### PR DESCRIPTION
**Pull request by dreik**
reducing noise in logs

N.B. to reduce the noise for existing hosts you'll have to edit every single host with http2 enabled and simply press save.

### CODE REVIEW

**Comment by jc21** [comment]
See #4075 this is already attempted, though is still WIP which is why I haven't looked at it too deeply

**Comment by dreik** [comment]
@jc21 sorry i've missed the PR you've mentioned as I've simply tried to fix the issues for myself. Meanwhile I've just checked all the comments left by @vladwing and proud to say that my PR already covered everything mentioned there.

**Comment by vladwing** [comment]
@jc21 you decide which one to accept, but this looks ready to me

**Comment by jc21** [comment]
Looks good to me

**Comment by DaanSelen** [comment]
So this warning is fixed in the upcoming version?

**Pull request merged**
