### PR TITLE
Use latest setuptools

### PR DESCRIPTION
**Pull request by dormancygrace**
I've checked setuptools 64 & 65 - all works as intended (tested on arm64)

### CODE REVIEW

**Comment by binhotvn** [comment]
Why you remove those lines instead of change version only?

**Comment by dormancygrace** [comment]
> Why you remove those lines instead of change version only?

Because there is no need to uninstall latest setuptools and then install version 58

**Comment by jc21** [comment]
The downgrade was initially required because of failing pip installs for certbot plugins. The only way your change can be tested as working is to install every certbot DNS plugin the app supports.

**Comment by dormancygrace** [comment]
> The downgrade was initially required because of failing pip installs for certbot plugins. The only way your change can be tested as working is to install every certbot DNS plugin the app supports.

I've tested reg.ru plugin, duckdns they work fine

**Pull request closed without merging**
