### PR TITLE
Enable PROXY procotol for proxy hosts and streams

### PR DESCRIPTION
**Pull request by snordmann**
As I see not too much progress in https://github.com/NginxProxyManager/nginx-proxy-manager/pull/3537, I decided to copy most of the code and (try to) fix the tests.
In this PR I also included the code necessary to enable the PROXY protocol for Streams.

Thank you @jwklijnsma for the previous work

### CODE REVIEW

**Comment by jc21** [comment]
CI is reporting:

```
Integration Tests / Mysql / Hosts endpoints.Should be able to create a http host

Error Message:
data should NOT have additional properties, data should have required property 'proxy_support_enabled'
```

**Comment by snordmann** [comment]
One question I do have: How should we show the user, that udp and proxy_protocol are exclusive options on a listener? Currently I just silently drop the proxy_protocol option for the UDP listener, but I am unsure that this is a good implementation.

I imagine that we could also disable the UDP button, when "Enable Proxy Protocol" is pressed.

**Comment by jwklijnsma** [comment]
> As I see not too much progress in #3537, I decided to copy most of the code and (try to) fix the tests. In this PR I also included the code necessary to enable the PROXY protocol for Streams.
> 
> Thank you @jwklijnsma for the previous work

The plan was to fix the test next week

**Comment by jwklijnsma** [comment]
what needs be done for mr @jc21

**Comment by qnlbnsl** [comment]
Any update on this?

**Comment by utopeadia** [comment]
Any latest news about proxy_protocol?

**Comment by snordmann** [comment]
@jc21 would you be able to merge this PR when I resolve all the conflicts?

**Comment by snordmann** [comment]
tbh, might be easier to start again from the current develop branch. I will close this PR and open a new one once I am done with the re-implementation.

**Pull request closed without merging**
