### PR TITLE
Add support for certbot-dns-multi

### PR DESCRIPTION
**Pull request by AridTag**

### CODE REVIEW

**Comment by AridTag** [comment]
For what it's worth I gave it a test for my use-case using the above CI build and it worked.
Use-case is DreamHost dns

**Comment by marcelrv** [comment]
> jc21/nginx-proxy-manager:github-pr-2402

Using this version I was successfully getting wildcard certificate using the certbot-dns-multi plugin.
Thanks. Would be great to have it merged.

**Comment by raphamotta** [comment]
+1

**Comment by k11i** [comment]
+1
Any new information about this?
AFAIU this would support a lot of additional DNS providers.
Thank you!

**Comment by KGBist2000** [comment]
+1

**Comment by joakimkingstrom** [comment]
+1
It'd be amazing if this could be integrated in the next release

**Comment by starsoccer** [comment]
Ive reapplied your change on develop hopefully someone will merge it 🤞  https://github.com/NginxProxyManager/nginx-proxy-manager/pull/3643

**Pull request closed without merging**
