### PR TITLE
Add Search Feature To Backend Administration 

### PR DESCRIPTION
**Pull request by ivankristianto**
### Add Search Feature To Backend Administration 

This PR allows user to do search query for all lists inside the backend administration.
These are the dashboard list that now has search function:
1. Proxy
2. Redirection
3. Stream
4. 404
5. Audit Logs
6. SSL Certificates
7. Users

The search query parameter is available and builtin from the api backend. This PR is to add the UI and the `query` param to the API.

Video Demo:

https://user-images.githubusercontent.com/656006/153700240-ead563ee-3623-4952-8813-ee89f4c95d7d.mp4

### CODE REVIEW

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 1 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1822`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Comment by jc21** [comment]
Awesome stuff, can't see anything wrong with it :) If you apply this to all the lists (where possible) then I'll put the PR through it's paces before merging. Thanks!

**Comment by ivankristianto** [comment]
Thanks @jc21 

Quick question: Should I continue to apply this to all possible list in this same PR or you prefer I separate it for each list?

**Comment by jc21** [comment]
Same PR please

**Comment by ivankristianto** [comment]
@jc21 This PR now completed and ready for your review / tests. 
The Jenkins CI has failed but not due to the code changes, And I cannot manually re-trigger it. I wonder what can I do to help?

**Comment by jc21** [comment]
This is an automated message from CI:

Docker Image for build 4 is available on [DockerHub](https://cloud.docker.com/repository/docker/jc21/nginx-proxy-manager) as `jc21/nginx-proxy-manager:github-pr-1822`

**Note:** ensure you backup your NPM instance before testing this PR image! Especially if this PR contains database changes.

**Pull request merged**
