### PR TITLE
added support for dns.he.net certbot plugin #2153

### PR DESCRIPTION
**Pull request by benhubert**

### CODE REVIEW

**Comment by benhubert** [comment]
I tested it with one of my personal top level domains + wildcard subdomain (such as `example.com,*.example.com`) using `jc21/nginx-proxy-manager:github-pr-2924` docker image and this worked :heavy_check_mark:

I also tried to get a certificate for a subdomain but sadly this does not work. :x:
I found https://github.com/tsaaristo/certbot-dns-he/issues/3 and https://github.com/tsaaristo/certbot-dns-he/pull/2 waiting for an answer of the maintainer since 2020 :unamused:

**Comment by amartins** [comment]
@benhubert I attempted to retrieve your image from DockerHub. However, I noticed that Hurricane Electric is not listed in the DNS Provider's dropdown menu.

Here's my docker-compose.yml file: 
```
version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:github-pr-2924'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt`
``` 

am I doing anything wrong?

**Comment by bgman111111** [comment]
hi im pissed. im using 2422 the latest nginx proxy manager and there is no he,net and itwas updted 4 days. is it only for version 3, becouse 2.10 there is no he.net i try version 3 and it dont respond, when try press hosts it dont open, maybe version 3 is not ready yet. and database is new, jc21 need to make for peoples who need to use nginx proxymanager version 3 compatible with nginx proxymanager version 2 database.

**Comment by rlcranney** [comment]
I also installed the image 'jc21/nginx-proxy-manager:github-pr-2924' and also don't see Hurricane Electric in the drop down list.
Here is my docker compose file
NPM_DockerCompose

Here is a screenshot of the DNS Provider's dropdown box.
NPM_DNS_Providers

**Comment by rlcranney** [comment]
@benhubert   I downloaded your pull request and noticed that on row 295, the password variable has spaces in it.  
I am definitely a newb when it comes to coding, but instead of my HE password, did you mean to write my_HE_password  ?

image

If I am off the mark, please know my intent it to get this resolved.  I am trying to be helpful, as I would really like Hurricane Electric to be a supported DNS Provider in NPM.  

I doubt this is what is keeping Hurricane Electric from appearing on the list, but thought I would inquire in case it is an issue.

@jc21  I don't know if requires verification label is an indication that you have to do something or a call for others to test / validate?   Is there anything I can do that will assist?

**Comment by jc21** [comment]
@rlcranney the label means someone, me or anyone, needs to test though in the case of the DNS providers, I don't use most of them so I rely on the community to test.

I'll merge this anyway, should it not work as intended, users can always roll back.

**Pull request merged**
